title: Settings
data:
  site_name: 'PHP Ain''t Dead Yet'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/rubio_tv'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/drbe4t'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:danny@rubio.tv'
      icon: site/social-icons/email.svg
